project 'SWBaseKit.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWBaseKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SWBaseKit
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Masonry', '~> 0.6.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension' #字典转模型
  pod 'MBProgressHUD'
  pod 'SDWebImage'

  target 'SWBaseKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SWBaseKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
